### PR TITLE
Use labels for hours provided by Untis API

### LINKED ISSUE #166: [Bug Report] Lesson "0" not being displayed correctly
**Description**

My school has a lesson "zero" in its schedule, which is not used by my lesson plan.
BetterUntis shows it as the first lesson, so the real first one is displayed as the second and so on. This can be quite confusing, if you have a quick look on your schedule.

Untis Mobile
BetterUntis

**Additional information**

 - Android version: _SailfishOS with AlienDalvik 8.1.0_
 - BetterUntis version: _3.4.4 (28)_
 - Installation source: _F-Droid_

### PR DESCRIPTION
**Pull request by DreamyLynn**
Untis sends explicit labels for hours, f.e. if the school has a lesson "0", see #166 
This displays the labels instead of counting up from 1, if there are any

Closes #166

### CODE REVIEW

File: app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt [hunk 1]
```diff
@@ -575,12 +575,16 @@ class MainActivity :
 
 			lines.add(startTimeInt)
 			lines.add(endTimeInt)
+			labels.add(hour.label)
```
Comment (SapuSeven) [inline app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt:578]: Why not check for empty labels right away?
```suggestion
			labels.add(if (hour.label.isBlank()) (index + 1).toString() else hour.label)
```

File: app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt [hunk 2]
```diff
@@ -575,12 +575,16 @@ class MainActivity :
...
 		}
 
 		if (!PreferenceUtils.getPrefBool(preferences, "preference_timetable_range_index_reset"))
 			weekView.hourIndexOffset = (range?.first ?: 1) - 1
 		weekView.hourLines = lines.toIntArray()
-
+		weekView.hourLabels = labels.toTypedArray().let { hourLabelArray ->
+			if(hourLabelArray.joinToString("")=="") IntArray(labels.size, fun(idx:Int):Int{return idx+1}).map{it.toString()}.toTypedArray()
+			else hourLabelArray
+		}
```
Comment (SapuSeven) [inline app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt:587]: (see above)
```suggestion
		weekView.hourLabels = labels.toTypedArray()
```

**Review by SapuSeven — COMMENTED** [review]
Thank you.
I just have one suggestion.

File: app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt (hunk 2 above)
Comment (DreamyLynn) [reply app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt:587]: I thought that, if there's a label missing for one hour, f.e. "0" does not have a label, but every other hour does, it would show "1, 1, 2, 3, ..." instead of just not putting a label for the first one. Schools do some weird stuff, so it wouldn't surprise me if that was a thing.

Comment (SapuSeven) [reply app/src/main/java/com/sapuseven/untis/activities/MainActivity.kt:587]: I see... yeah you're right.

**Review by SapuSeven — APPROVED** [review]
