### PR TITLE
Fix Widgets on Android 12

### LINKED ISSUE #238: [Bug Report] Crash when placing widgets on Android 12
<details>
<summary>Logs</summary>

[logs-1640962303548.zip](https://github.com/SapuSeven/BetterUntis/files/7796463/logs-1640962303548.zip)

</details>

**Additional information**

- Android version: _12_
- BetterUntis version: _3.4.7 (31)_
- Installation source: _fdroid_

### PR DESCRIPTION
**Pull request by DreamyLynn**
closes #238

### CODE REVIEW

File: app/src/main/java/com/sapuseven/untis/widgets/BaseWidget.kt [hunk 1]
```diff
@@ -84,7 +85,11 @@ open class BaseWidget : AppWidgetProvider() {
 
 		val updateIntent = Intent(context, this.javaClass)
 				.setAction(AppWidgetManager.ACTION_APPWIDGET_UPDATE)
-		val pendingIntent = PendingIntent.getBroadcast(context, 0, updateIntent, PendingIntent.FLAG_UPDATE_CURRENT)
+		val pendingIntent = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
+			PendingIntent.getBroadcast(context, 0, updateIntent, PendingIntent.FLAG_UPDATE_CURRENT + PendingIntent.FLAG_IMMUTABLE)
```
Comment (SapuSeven) [inline app/src/main/java/com/sapuseven/untis/widgets/BaseWidget.kt]: Flags are combined using `|`
```suggestion
			PendingIntent.getBroadcast(context, 0, updateIntent, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE)
```

**Review by SapuSeven — DISMISSED** [review]
Untested, but looks good.

**Review by SapuSeven — DISMISSED** [review]

**Review by SapuSeven — APPROVED** [review]
